### ISSUE TITLE
gedit-gmate repository error in Ubuntu 17.10

### ISSUE THREAD

**Issue by shakarim22s** [gmate/gmate#184]
Ign:8 http://ppa.launchpad.net/ubuntu-on-rails/ppa/ubuntu artful InRelease                                                                                            
Err:9 http://ppa.launchpad.net/ubuntu-on-rails/ppa/ubuntu artful Release                                                                                              
  404  Not Found
Reading package lists... Done                                                                                                                                         
E: The repository 'http://ppa.launchpad.net/ubuntu-on-rails/ppa/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by sigstart** [comment]
Thanks for the error report. I don't really use Ubuntu on daily basis anymore, but I'll see if I can make a new build and update the PPA.

**Comment by xuwangly** [comment]
It looks same with the bug#185.

**Comment by sigstart** [comment]
Apologies, I never got around to this. Since Ubuntu 17.10 is no longer being supported, I imagine that it would no longer be useful to fix this.

I have created a package for Bionic (18.04 LTS) and it is currently waiting for its turn in the PPA build queue. If you're running the LTS, then you should be able to get Gmate soon. (It also fixes #185).

Next on my list is trying to make TextMap work in gedit3 (#186), then I'll spin up an Eoan (19.10) virtual machine and create its PPA packages.
